export const categoryOptions = [
  {
    icon: "💻",
    text: "Coding",
    value: "coding",
    id: "1",
    label: "💻  Coding",
    src: "https://res.cloudinary.com/dpvigehxt/image/upload/v1655009810/categoryImagesActivities/coding_aqhyl7.jpg",
  },
  {
    icon: "🖼",
    text: "Art&Design",
    value: "artdesign",
    id: "2",
    label: "🖼  Art&Design",
    src: "https://res.cloudinary.com/dpvigehxt/image/upload/v1655009809/categoryImagesActivities/artdesign_oxwrrt.jpg",
  },
  {
    icon: "🎮",
    text: "Videogames",
    value: "videogames",
    id: "3",
    label: "🎮  Videogames",
    src: "https://res.cloudinary.com/dpvigehxt/image/upload/v1655009810/categoryImagesActivities/videogames_cpuzn4.jpg",
  },
  {
    icon: "🍿",
    text: "Watch",
    value: "watch",
    id: "4",
    label: "🍿  Watch",
    src: "https://res.cloudinary.com/dpvigehxt/image/upload/v1655009810/categoryImagesActivities/watch_xdstqp.jpg",
  },
  {
    icon: "💰",
    text: "Business",
    value: "business",
    id: "5",
    label: "💰  Business",
    src: "https://res.cloudinary.com/dpvigehxt/image/upload/v1655009809/categoryImagesActivities/business_eurqf9.jpg",
  },
  {
    icon: "📖",
    text: "Study",
    value: "study",
    id: "6",
    label: "📖  Study",
    src: "https://res.cloudinary.com/dpvigehxt/image/upload/v1655009810/categoryImagesActivities/study_rbimdb.jpg",
  },
  {
    icon: "🎶",
    text: "Music",
    value: "music",
    id: "7",
    label: "🎶  Music",
    src: "https://res.cloudinary.com/dpvigehxt/image/upload/v1655009810/categoryImagesActivities/music_g2mv4e.jpg",
  },
  {
    icon: "🤹",
    text: "Content",
    value: "content",
    id: "8",
    label: "🤹  Content",
    src: "https://res.cloudinary.com/dpvigehxt/image/upload/v1655009811/categoryImagesActivities/content_tae75q.jpg",
  },
  {
    icon: "👋",
    text: "Misc.",
    value: "misc",
    id: "9",
    label: "👋  Misc.",
    src: "https://res.cloudinary.com/dpvigehxt/image/upload/v1655009810/categoryImagesActivities/misc_erdmt5.jpg",
  },
];
