export const categoryOptions = [
  { icon: "💻", text: "Coding", value: "coding", id: "1", label: "💻  Coding" },
  {
    icon: "🖼",
    text: "Art&Design",
    value: "artdesign",
    id: "2",
    label: "🖼  Art&Design",
  },
  {
    icon: "🎮",
    text: "Videogames",
    value: "videogames",
    id: "3",
    label: "🎮  Videogames",
  },
  { icon: "🍿", text: "Watch", value: "watch", id: "4", label: "🍿  Watch" },
  {
    icon: "💰",
    text: "Business",
    value: "business",
    id: "5",
    label: "💰  Business",
  },
  { icon: "📖", text: "Study", value: "study", id: "6", label: "📖  Study" },
  { icon: "🎶", text: "Music", value: "music", id: "7", label: "🎶  Music" },
  {
    icon: "🤹",
    text: "Content",
    value: "content",
    id: "8",
    label: "🤹  Content",
  },
  { icon: "👋", text: "Misc.", value: "misc", id: "9", label: "👋  Misc." },
];
